### ISSUE TITLE
This thing

### ISSUE THREAD

**Issue by brotherlogic** [brotherlogic/discovery#46]
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x17b860]

goroutine 1 [running]:
panic(0x3af030, 0x10822008)
	/usr/local/go/src/runtime/panic.go:500 +0x33c
google.golang.org/grpc.(*Server).Serve.func1(0x10948000, 0x0, 0x0)
	/home/simon/code/src/google.golang.org/grpc/server.go:445 +0xa0
panic(0x3af030, 0x10822008)
	/usr/local/go/src/runtime/panic.go:458 +0x454
google.golang.org/grpc.(*Server).Serve(0x10948000, 0x0, 0x0, 0x0, 0x0)
	/home/simon/code/src/google.golang.org/grpc/server.go:454 +0x1a8
main.Serve()
	/home/simon/code/src/github.com/brotherlogic/discovery/discoveryapi.go:40 +0x22c
main.main()
	/home/simon/code/src/github.com/brotherlogic/discovery/discoveryapi.go:45 +0x14

**Comment by brotherlogic** [comment]
Fixed
