### ISSUE TITLE
Fixy Dixy

### ISSUE THREAD

**Issue by brotherlogic** [brotherlogic/discovery#47]
goroutine 350481 [running]:
panic(0x3af030, 0x10822030)
	/usr/local/go/src/runtime/panic.go:500 +0x33c
main.(*Server).cleanEntries(0x108575a0)
	/home/simon/code/src/github.com/brotherlogic/discovery/discovery.go:83 +0x344
main.(*Server).ListAllServices(0x108575a0, 0x75339030, 0x12421700, 0x589c0c, 0x0, 0x0, 0x0)
	/home/simon/code/src/github.com/brotherlogic/discovery/discovery.go:93 +0x50
github.com/brotherlogic/discovery/proto._DiscoveryService_ListAllServices_Handler(0x3d8258, 0x108575a0, 0x75339030, 0x12421700, 0x147ae030, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/simon/code/src/github.com/brotherlogic/discovery/proto/discovery.pb.go:191 +0xf8
google.golang.org/grpc.(*Server).processUnaryRPC(0x1092c000, 0x559b68, 0x12f24a80, 0x11ee34d0, 0x108578a0, 0x577090, 0x12421760, 0x0, 0x0)
	/home/simon/code/src/google.golang.org/grpc/server.go:797 +0x1100
google.golang.org/grpc.(*Server).handleStream(0x1092c000, 0x559b68, 0x12f24a80, 0x11ee34d0, 0x12421760)
	/home/simon/code/src/google.golang.org/grpc/server.go:997 +0xde4
google.golang.org/grpc.(*Server).serveStreams.func1.1(0x15c2c4b0, 0x1092c000, 0x559b68, 0x12f24a80, 0x11ee34d0)
	/home/simon/code/src/google.golang.org/grpc/server.go:561 +0x9c
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/simon/code/src/google.golang.org/grpc/server.go:562 +0x98

**Comment by brotherlogic** [comment]
Added some logging statements to help debug this
